export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCEEDED = 'SIGN_IN_SUCCEEDED';
export const SIGN_OUT = 'SIGN_OUT';
export const CHECK_AUTH_TIMEOUT = 'CHECK_AUTH_TIMEOUT';
export const STOP_AUTH_TIMER = 'STOP_AUTH_TIMER';
export const AUTO_SIGN_IN = 'AUTO_SIGN_IN';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

