export const FETCH_HOTELS = 'FETCH_HOTELS';
export const SET_HOTELS = 'SET_HOTELS';
export const FETCH_HOTEL_PHOTOS = 'FETCH_HOTEL_PHOTOS';
export const SET_HOTEL_PHOTOS = 'SET_HOTEL_PHOTOS';
export const SELECT_HOTEL = 'SELECT_HOTEL';
