export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';
export const SET_CITIES = 'SET_CITIES';
export const SELECT_CITY = 'SELECT_CITY';
